### ISSUE TITLE
Link issue with a Markdown library

### ISSUE THREAD

**Issue by LutfiTekin** [saket/Better-Link-Movement-Method#15]
Hi there, 
First I want to thank you for this library I have been using it for a long time.
Lately I have decided to support markdown in my app and I tried to use this [one](https://github.com/noties/Markwon/blob/master/README.md) 
Here's my problem
When I add a link like this
`[inline-style link](https://www.google.com)`
LinkClick listener gets url as **inline-style link**  not **https://www.google.com**
I couldn't really tell which library caused this but I wanted to ask you anyway

**Comment by saket** [comment]
@LutfiTekin this was partly a problem with Markwon and partly a limitation of this library. Markwon has already pushed a fix in v1.0.5, but it's not released yet. You can use jitpack.io to get the latest build in the meanwhile.

You can read more here: https://github.com/noties/Markwon/issues/34
