### ISSUE TITLE
it do not work when use textview.setText("https://goo.gl/maps/KfRBC6KLHA12")

### ISSUE THREAD

**Issue by luwies** [saket/Better-Link-Movement-Method#18]

**Comment by luwies** [comment]
i has find the reason, after textview.setText("https://goo.gl/maps/KfRBC6KLHA12") should call BetterLinkMovementMethod.linkify(Linkify.ALL, this)
            .setOnLinkClickListener(urlClickListener)
            .setOnLinkLongClickListener(longClickListener);

**Comment by saket** [comment]
That sounds correct. Texts are not linkified automatically when you apply them on a TextView.
