### ISSUE TITLE
   \n - new line is not working. "Click here" is not moving to new line

### ISSUE THREAD

**Issue by maheswaranecemohan** [saket/Better-Link-Movement-Method#19]
Or issue with your app, your loan or our products and services you can contact us using any of the above methods.    \n <a href="https://www.google.com">Click here</a> to see more information about our complaints procedure.

**Comment by maheswaranecemohan** [comment]
<string name="bettermovementmethod_dummy_text_long"><![CDATA[
Or issue with your app, your loan or our products and services you can contact us using any of the above methods.    \n <a href="https://www.satsumaloans.co.uk/existing-customers/complaints">Click here</a> to see more information about our complaints procedure.
    ]]></string>

**Comment by maheswaranecemohan** [comment]
Or issue with your app, your loan or our products and services you can contact us using any of the above methods.    \n <a href="https://www.google.com">Click here</a> to see more information about our complaints procedure.

**Comment by saket** [comment]
Closing as spam.
