### ISSUE TITLE
Please reduce minSdk to 14

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [saket/Better-Link-Movement-Method#23]
Seems it still works fine...

**Comment by AndroidDeveloperLB** [comment]
Hmmmm... I was wrong.
The library uses this:

`    BackgroundColorSpan highlightSpan = new BackgroundColorSpan(textView.getHighlightColor());
`

Any alternative to this?

**Comment by saket** [comment]
You could potentially recreate the span because all it does is set `TextPaint#bgColor`, but the APIs for `ParcelableSpan` are internal so it's not a very good option.

**Comment by AndroidDeveloperLB** [comment]
I think I got something .

How about this:

```
        int hightlightColor;
        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
            hightlightColor = textView.getHighlightColor();
        } else {
            try {
                Field highlightPaintField = textView.getClass().getDeclaredField("mHighlightPaint");
                highlightPaintField.setAccessible(true);
                final Paint highlightPaint = (Paint) highlightPaintField.get(textView);
                hightlightColor = highlightPaint.getColor();
            } catch (Exception e) {
                e.printStackTrace();
                int textColor = textView.getTextColors().getDefaultColor();
                int linkColor = textView.getLinkTextColors().getDefaultColor();
                int textAndLinkColorAverage = Color.rgb((Color.red(textColor) + Color.red(linkColor)) / 2,
                        (Color.green(textColor) + Color.green(linkColor)) / 2,
                        (Color.blue(textColor) + Color.blue(linkColor)) / 2);
                if (textAndLinkColorAverage == textColor || textAndLinkColorAverage == linkColor)
                    hightlightColor = Color.rgb(255 - Color.red(textAndLinkColorAverage),
                            255 - Color.green(textAndLinkColorAverage),
                            255 - Color.blue(textAndLinkColorAverage));
                else hightlightColor = textAndLinkColorAverage;
            }
        }
        BackgroundColorSpan highlightSpan = new BackgroundColorSpan(hightlightColor);
```

**Comment by saket** [comment]
Ah, I thought it was `BackgroundColorSpan` that's only available on 21+. 

I don't think I want to include this workaround in the library. Do you want to maintain a fork that backports this library to 14?

**Comment by AndroidDeveloperLB** [comment]
Are you sure? It seems to work very well now.

And, I've also made the sample to work, even though it was set for some reason to work only from API 23 instead of 16 ...

Here:

https://github.com/saket/Better-Link-Movement-Method/pull/24

**Comment by saket** [comment]
Yep. I strongly think using `minSdk` as 21 is the way to go forward, unless you really want to target ~6 year old devices.

This solution may work, but using reflection is always a hacky solution. Sorry :)

**Comment by saket** [comment]
Closing this because I still don't think this library should maintain workarounds to support old devices.
