### ISSUE TITLE
linkifyHtml and linkify (WER_URLS) are not working together

### ISSUE THREAD

**Issue by jamolkhon** [saket/Better-Link-Movement-Method#25]
I have texts with `<a href="url">abc</a>` and urls that are not inside <a> tag. I would like to turn both to spannable links. So far it's not working. Only linkifyHtml is being applied.

**Comment by saket** [comment]
Whoops, I completely missed this. @jamolkhon did you manage to solve this? If not, can you share your full string, how you're applying it to your `TextView` and how `BetterLinkMovementMethod` is set?

**Comment by jamolkhon** [comment]
No, I tried a few variations. Also tried to reorder linkify method calls. It didn't help. Currently, I'm turning urls to <a> tags then using only linkifyHtml.

**Comment by saket** [comment]
Cool 👍
