### ISSUE TITLE
Two types of links in one TextView

### ISSUE THREAD

**Issue by JEuler** [saket/Better-Link-Movement-Method#26]
Hi! I have the following issue. If I have two types of links in one TextView (e.g. `<a href="link">label</a>` and `https://example.com` one of the links will not be clickable. I see that this is so for the standard Linkify method. Did you saw something like that?

**Comment by jamolkhon** [comment]
See #25.

**Comment by JEuler** [comment]
Thank you! Could you share the code for the `turning urls to tags`?

**Comment by saket** [comment]
Closing this because this does not seem related to this library. `Better-Link-Movement-Method` is only responsible for handling clicks on clickable spans. Please feel free to reopen this.
