### ISSUE TITLE
Recyclerview scrolls automatically

### ISSUE THREAD

**Issue by sidtact** [saket/Better-Link-Movement-Method#28]
I am using this lib with Markwon. markwon is parsing html urls and the i am applying Linkify Spans over it. it is working but when i scroll recyclerview up and click on any link nothing happens and recyclerview scrolls up by 1 page

**Comment by saket** [comment]
I guess you've already figured this out. For the record, I think this is a problem with the layout. I have seen this happening when focusable views are present inside a RecyclerView. Is this correct, @sidtact?

**Comment by sidtact** [comment]
@saket well.... actually i was only having textviews and my rescycler view was having descendent focusability  to block descendent but it did not help. At the end I found that this is caused by line Selection.setSelection in highlightLink, I still dont know the reason why its happening on that line.

**Comment by saket** [comment]
Ah okay. 🙂👍
