### ISSUE TITLE
Espresso Testing Support

### ISSUE THREAD

**Issue by ibrahimyilmaz** [saket/Better-Link-Movement-Method#36]
As an Android Developer, we would like to implement instrumentation test if we behave correctly or not. 
So we need to be able to fire the click. If possible can you add this functionality?

**Comment by saket** [comment]
Are you asking for custom ViewMatchers for Espresso that helps you test link clicks?

**Comment by ibrahimyilmaz** [comment]
Exactly how can we click the link?

**Comment by saket** [comment]
`ViewActions` has a few `openLink*()` functions for opening links. Have you tried using them?

**Comment by ibrahimyilmaz** [comment]
Oh thanks! Maybe we can put some information in the readme for someone who is not aware of `openLink`. I close the issue.
